import { Space } from '@/types'

export const MOCK_SPACES: Space[] = [
  {
    id: 'space-001',
    name: '애월 오션뷰 코워킹',
    description: '제주 애월 해안도로에 위치한 오션뷰 코워킹 공간. 넓은 창문으로 바다를 바라보며 집중할 수 있어요.',
    region: 'jeju',
    address: '제주 제주시 애월읍 애월해안로 000',
    lat: 33.46,
    lng: 126.31,
    type: 'coworking',
    pricePerDay: 45000,
    pricePerMonth: 800000,
    wifiSpeed: 500,
    noiseLevel: 2,
    hasPrivateRoom: true,
    hasMonitor: true,
    hasPrinter: true,
    nearNature: true,
    images: [],
    rating: 4.8,
    reviewCount: 127,
    tags: ['오션뷰', '조용함', '집중', '모니터 제공'],
    createdAt: '2026-01-01',
  },
  {
    id: 'space-002',
    name: '한림 감성 카페 스테이',
    description: '제주 한림의 작은 감성 카페. 오전은 코워킹으로 오후는 카페로 운영돼 시간대별 분위기가 달라요.',
    region: 'jeju',
    address: '제주 제주시 한림읍 한림로 000',
    lat: 33.41,
    lng: 126.27,
    type: 'cafe',
    pricePerDay: 25000,
    pricePerMonth: null,
    wifiSpeed: 200,
    noiseLevel: 3,
    hasPrivateRoom: false,
    hasMonitor: false,
    hasPrinter: false,
    nearNature: true,
    images: [],
    rating: 4.6,
    reviewCount: 89,
    tags: ['감성', '카페', '자연', '여유'],
    createdAt: '2026-01-15',
  },
  {
    id: 'space-003',
    name: '속초 산속 워케이션 빌라',
    description: '설악산이 보이는 산속 빌라. 완전한 고독과 자연 속에서 깊은 집중을 원하는 분께 추천해요.',
    region: 'gangwon',
    address: '강원 속초시 설악동 000',
    lat: 38.19,
    lng: 128.56,
    type: 'villa',
    pricePerDay: 120000,
    pricePerMonth: 2000000,
    wifiSpeed: 300,
    noiseLevel: 1,
    hasPrivateRoom: true,
    hasMonitor: true,
    hasPrinter: false,
    nearNature: true,
    images: [],
    rating: 4.9,
    reviewCount: 43,
    tags: ['산속', '고독', '집중', '자연', '프리미엄'],
    createdAt: '2026-02-01',
  },
  {
    id: 'space-004',
    name: '강릉 바다 앞 코워킹',
    description: '강릉 경포 해수욕장 앞에 위치한 코워킹 공간. 파도 소리를 들으며 작업할 수 있어요.',
    region: 'gangwon',
    address: '강원 강릉시 경포로 000',
    lat: 37.79,
    lng: 128.91,
    type: 'coworking',
    pricePerDay: 35000,
    pricePerMonth: 600000,
    wifiSpeed: 1000,
    noiseLevel: 2,
    hasPrivateRoom: false,
    hasMonitor: true,
    hasPrinter: true,
    nearNature: true,
    images: [],
    rating: 4.7,
    reviewCount: 156,
    tags: ['바다뷰', '기가인터넷', '핫플', '코워킹'],
    createdAt: '2026-01-20',
  },
  {
    id: 'space-005',
    name: '여수 낭만항구 펜션 오피스',
    description: '여수 돌산도의 낭만적인 항구 뷰 펜션. 별채 작업실이 있어 독립적인 업무 환경을 제공해요.',
    region: 'jeonnam',
    address: '전남 여수시 돌산읍 000',
    lat: 34.71,
    lng: 127.73,
    type: 'pension',
    pricePerDay: 90000,
    pricePerMonth: 1500000,
    wifiSpeed: 400,
    noiseLevel: 1,
    hasPrivateRoom: true,
    hasMonitor: false,
    hasPrinter: false,
    nearNature: true,
    images: [],
    rating: 4.8,
    reviewCount: 67,
    tags: ['낭만', '항구뷰', '독립작업실', '프라이빗'],
    createdAt: '2026-02-10',
  },
  {
    id: 'space-006',
    name: '부산 해운대 도심 코워킹',
    description: '해운대 번화가에 위치한 세련된 코워킹 공간. 네트워킹과 미팅에 최적화된 환경이에요.',
    region: 'busan',
    address: '부산 해운대구 해운대해변로 000',
    lat: 35.16,
    lng: 129.16,
    type: 'coworking',
    pricePerDay: 40000,
    pricePerMonth: 700000,
    wifiSpeed: 1000,
    noiseLevel: 3,
    hasPrivateRoom: true,
    hasMonitor: true,
    hasPrinter: true,
    nearNature: false,
    images: [],
    rating: 4.5,
    reviewCount: 201,
    tags: ['도심', '네트워킹', '미팅룸', '세련됨'],
    createdAt: '2026-01-10',
  },
]
